package io.pulsekit.android

import android.content.Context
import io.github.aakira.napier.Napier
import io.pulsekit.core.BuildProvenance
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json

/**
 * Reads the build-time provenance resource generated by the app's Gradle build
 * (`pulsekit_provenance.json` in assets — see the sample's `build.gradle.kts`).
 * No git at runtime — a pure asset load. Missing/invalid → [BuildProvenance.EMPTY].
 */
internal object PulseProvenance {

    private val json = Json { ignoreUnknownKeys = true }
    private const val ASSET_NAME = "pulsekit_provenance.json"

    fun load(context: Context): BuildProvenance = try {
        context.assets.open(ASSET_NAME).bufferedReader().use { reader ->
            json.decodeFromString<BuildProvenance>(reader.readText())
        }
    } catch (e: Exception) {
        Napier.d { "No build provenance asset ($ASSET_NAME): ${e.message}" }
        BuildProvenance.EMPTY
    }
}
